version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Logging into ECR..."
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 720237151009.dkr.ecr.us-east-1.amazonaws.com)

  pre_build:
    commands:
      - echo "Preparing Docker image..."
      - docker build -t sholate-motors-build-env .
      - docker tag sholate-motors-build-env:latest 720237151009.dkr.ecr.us-east-1.amazonaws.com/sholate-motors-build-env:latest

  build:
    commands:
      - echo "Starting build..."
      - npm run build
      - echo "Running tests..."
      - npm test || echo "No tests found, skipping..."
      - echo "Running security scan..."
      - npm audit --audit-level=high
      - echo "Pushing Docker image to ECR..."
      - docker push 720237151009.dkr.ecr.us-east-1.amazonaws.com/sholate-motors-build-env:latest
      - echo "Build complete!"

reports:
  test-report:
    files:
      - '**/TEST-*.xml'
    discard-old-reports: yes

artifacts:
  files:
    - '**/*'
