version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running lint check..."
      - npm run lint || echo "No lint script found"

  build:
    commands:
      - echo "Building Sholate Motors application..."
      - npm run build || echo "No build script found"

  post_build:
    commands:
      - echo "Running smoke tests..."
      - npm test || echo "No test script found"
      - echo "Build completed successfully on $(date)"

artifacts:
  files:
    - '**/*'
  discard-paths: no
