version: 0.2

env:
  variables:
    NODE_ENV: "development"       # default environment

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "Running tests with coverage..."
      - npm test -- --coverage

  build:
    commands:
      - echo "Building project for $NODE_ENV environment..."
      # Example: if you have build scripts per environment
      - if [ "$NODE_ENV" == "production" ]; then npm run build:prod; else npm run build; fi

  post_build:
    commands:
      - echo "Build complete for $NODE_ENV environment!"

cache:
  paths:
    - node_modules/**/*     # cache dependencies to speed up next build
