version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install -g npm@10
      - npm install
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI

  pre_build:
  commands:
    - echo "Preparing Docker image..."
    - echo "Listing files in current directory for debug:"
    - ls -la
    - echo "Building Docker image..."
    - docker build -t $IMAGE_NAME -f ./Dockerfile .
    - docker tag $IMAGE_NAME:latest $ECR_URI:latest


  build:
    commands:
      - echo "Starting build..."
      - npm run build
      - echo "Running tests..."
      - npm test || echo "No tests found, skipping..."
      - echo "Running security scan..."
      - npm audit --audit-level=high
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_URI:latest
      - echo "Build complete!"

reports:
  test-report:
    files:
      - '**/TEST-*.xml'

artifacts:
  files:
    - '**/*'
